### ISSUE TITLE
UI Web site: Update Wallet and fix logo of website

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/themarquis-ui-sc#71]
## Issue Overview

1. Update marquis wallet interface based on new design.
2. When search marquis on "google", it shows a white logo and repetitve domain 'xyz'.
![image](https://github.com/user-attachments/assets/65077a1e-d45f-42e6-929a-28821555480f)

### Wallet
- Implement design (new wallet dropdown - first part) [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5274&node-type=section&t=wQYAxVCgHjbwNz9d-0).

### Google search result
- Use this [App-logo.zip](https://github.com/user-attachments/files/17771985/App-logo.zip) to update the logo
- Make sure the favicon work well on dark mode & light mode
- Replace `themarquis.xyz` with `The Marquis`

**Comment by NueloSE** [comment]
@gianalarcon kindly assign me the above issue I can handle this issue worked on something similar to this before. ETA <=24hrs

**Comment by petersdt** [comment]
I’d like to help with this.

**Comment by joeperpetua** [comment]
gm would love to work on this issue

**Comment by Kingsuite** [comment]
Can I be assigned to this?

**Comment by SudiptaPaul-31** [comment]
Can I take this issue?

My approach to tackle this issue:

Updating the wallet dropdown ui based on the provided new design.
Updating the new logo provided.
Verifying the changes being made.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 72hrs. Thanks

**Comment by ShantelPeters** [comment]
May I take this issue on?

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by gianalarcon** [comment]
All yours @NueloSE  We expected is issue to be solved soon. Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not our main branch

**Comment by gianalarcon** [comment]
Hi @NueloSE. Any updates on this? We expect at least a draft PR in the upcoming hours. Thanks!

**Comment by NueloSE** [comment]
@gianalarcon make a PR soon

**Comment by HungNDB** [comment]
I'd love to work on this!

**Comment by OWK50GA** [comment]
I’d love to work on this task.

**Comment by amJoe-dev** [comment]
May I be assigned to this?

**Comment by mimisavage** [comment]
I'd love to work on this!

**Comment by aniruddhaaps** [comment]
To ddress the problem, I would:
Wallet Interface: Replace wallet dropdown design update. After that, integration and testing should be done on all devices without any issues.
Google Search Result: Update the favicon and logo with the attached App-logo.zip file so that it displays correctly in light and dark. Update metadata to read "The Marquis" instead of themarquis.xyz.
Test the changes to be sure they reflect consistently across search engines as well as within the application. Submit a PR to the develop branch.

**Comment by Luluameh** [comment]
Let me handle this issue!

**Comment by gianalarcon** [comment]
closed with #86
