### ISSUE TITLE
UI Web site: Enable/Fix Download button

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/themarquis-ui-sc#72]
### On PC version

In the marquis [website](https://themarquis.xyz/), currently the download button redirect you to a drive file. 
![image](https://github.com/user-attachments/assets/4bb55901-ed47-432d-9c65-5c65db76aba5)

Also enable/fix the footer for discord and Donwload
![image](https://github.com/user-attachments/assets/b8c9c456-3fad-4564-81d5-a96699e3c73d)

### On Mobile version

- Enable icons to be clickable/touchable 
- Only display the correctly download app detected (CHPlay or Appstore)

![Screenshot_20241115_152520_com android chrome_edit_264004673379735](https://github.com/user-attachments/assets/5bf184c5-f793-4bfb-886e-3bbca1de70ca)

## Proposed Solutions or Ideas

[Here](https://linktr.ee/themarquis_) you can find the link of google play and app store. 

- Visit from android mobile, it should open the Marquis app on google play
- Visit from iOS it should open the Marquis app on app store.
- Visit from website, it should be show the notification message warning "Only support on mobile" when the button have clicked

**Comment by Iwueseiter** [comment]
Hi @gianalarcon can I work on this?
I’m a frontend and smart developer, I’d quickly implement this as expected.
Kindly assign.

**Comment by gianalarcon** [comment]
Issues will be assigned on Nov 21th, thanks!

**Comment by PedroCo3lho** [comment]
Helo @gianalarcon, can I implement this as my first issue in the repo?

**Comment by mayasimi** [comment]
Could I be assigned to this?

**Comment by joeperpetua** [comment]
gm would love to work on this issue

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by CollinsC1O** [comment]
I’d like to help with this.

**Comment by Supa-mega** [comment]
Is it okay if I take this?

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 72hrs. Thanks

**Comment by PedroCo3lho** [comment]
> Helo @gianalarcon, can I implement this as my first issue in the repo?
I’m a full-stack developer with a solid understanding of TypeScript, Next.js, and TailwindCSS. The task and development flow are clear to me. 
Please let me know if I can start so I can deliver it asap!

**Comment by ShantelPeters** [comment]
I’d like to work on this.

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by gianalarcon** [comment]
All yours @melnikga.  Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not our main branch

**Comment by gianalarcon** [comment]
Hi @melnikga. Any updates on this? We expect at least a draft PR in the upcoming hours. Thanks!

**Comment by melnikga** [comment]
Hi, @gianalarcon! I'll send the result in the next few hours)

**Comment by gianalarcon** [comment]
Closed with #80
