### ISSUE TITLE
UI Web site[draft]: Fix Loading after login/signup

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/themarquis-ui-sc#73]
## Issue Overview
- Implement a loading when redirect to another page

## Proposed Solutions or Ideas
- Add suspend loading page (need to check prototype) , [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3512-8180&node-type=frame&t=wQYAxVCgHjbwNz9d-0)

**Comment by PedroCo3lho** [comment]
Hi, I'm Pedro a full-stack dev, i have a background using frontend technologies such as Next.JS, TailwindCSS, DaisyUI, Motion and DaisyUI. I plan to implement a `loading.tsx` file to handle the `.gif` provided in the Figma design, and whenever an interaction requires a loading event, we can call this `loading.tsx` component.
Let me know if I can work on this!
