### ISSUE TITLE
UI Web site: Fix Landing page and Fix Mobile responsive (Banner, sign-in/sign-up)

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/themarquis-ui-sc#74]
### Landing Page

- Update Landing Page to match with provided design, pay attention to the details [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5273&node-type=section&t=VbsLmNRi97qWmyNZ-0)

### Login/Signup Page
- Implement UI match with new Figma [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5273&node-type=section&t=Ml3tHeDpoLpDEWyZ-0)

### Responsive
- Implement responsive Login/Signup page for Mobile [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3193-2257&node-type=section&t=VbsLmNRi97qWmyNZ-0)
- Implement responsive Login/Signup page for Tablet [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-8640&node-type=section&t=VbsLmNRi97qWmyNZ-0)
- Implement responsive Twitter invite post [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3158-5373&node-type=section&t=VbsLmNRi97qWmyNZ-0)

### Landing Page
- Fix based on provided design. Google play and app store logos
- Fix carousel : match size for active slide & inactive slide, make sure mobile version work well
- Fix align space between sections
- Fix effect at "Sign up now" button

### Login/Signup Page
- Fix based on new background

### Mobile responsive
- Fix based on provided design

**Comment by Immanuelolivia1** [comment]
Would love to tackle this!

**Comment by 0xdevcollins** [comment]
Can I tackle this one?

**Comment by Hoossayn** [comment]
Can i work on this ?

**Comment by Alfred-Emmanuel** [comment]
Why i think i'm the right person for this

I am a software engineer(frontend) with 4 years of hands on experience and i am an avid open source contributor, i also participated in the just concluded hacktoberfest,
the ETA for this if i'm assigned to it would be 48hrs

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Supa-mega** [comment]
Could I take a shot at this?

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 72hrs. Thanks

**Comment by ShantelPeters** [comment]
Would love to tackle this!

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by Amarjeet325** [comment]
Can I take this from here?

**Comment by akintola4** [comment]
I'm eager to contribute my design skills to this hackathon. My recent work on (https://webfleets.vercel.app/) involved revamping the landing page. This experience in Frontend UI development  and mobile optimization aligns perfectly with the demands of hackathon environment. I'm confident in my ability to deliver innovative and user-centric solutions.

**Comment by akintola4** [comment]
As a skilled React developer, I'm eager to contribute my expertise to this hackathon. My experience in building (https://webfleets.vercel.app/) has honed my ability to deliver efficient, scalable, and user-friendly web applications. I'm excited to collaborate with a talented team and leverage my problem-solving skills to tackle challenging problems and deliver innovative solutions.

**Comment by pheobeayo** [comment]
Let me handle this issue!

**Comment by gianalarcon** [comment]
All yours @josephchimebuka. Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not our main branch

**Comment by josephchimebuka** [comment]
> All yours @josephchimebuka. Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not our main branch

Alright noted @gianalarcon I'm on it and I will send PR ASAP

**Comment by gianalarcon** [comment]
Hi @josephchimebuka . Could you please share an update? We're expecting to see at least a draft PR within the next few hours. Thanks!

**Comment by gianalarcon** [comment]
closed with #88
