### ISSUE TITLE
Implement responsive Brandkit page & Loading component

### ISSUE THREAD

**Issue by Buuh2511** [The-Marquis-Gaming/themarquis-ui-sc#78]
## Issue Overview
- [ ] 1. Upgrade PC version to new Figma
- [ ] 2. Implement responsive Brandkit UI page [here](https://www.figma.com/design/Ybq9WIO2OrdTHH21yH1Ty9/The-Marquis-Brandkit-(Only-Dust)?node-id=1-179&node-type=frame&t=iV1O7UXzoIfHGNA9-0) via : /brandkit
- [ ] 3. Implement a loading when redirect to another page

## Proposed Solutions or Ideas
- Add suspend loading page (need to check prototype) , [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3512-8180&node-type=frame&t=wQYAxVCgHjbwNz9d-0)
- Add [this part](https://www.figma.com/design/Ybq9WIO2OrdTHH21yH1Ty9/The-Marquis-Brandkit-(Only-Dust)?node-id=1-46&node-type=frame&t=sP4YLXyPeKn04aHz-0) to Color section 

## Final result
Expect correctly a hundred percent for version width : 390px & PC version
Resonpisve should work well on every screen
Loading components must be preloaded whenever needed

## Note
Drop PR base on develop branch
Implementation time is 24 hours from assignment

**Comment by petersdt** [comment]
@Buuh2511 @gianalarcon can i be assigned the above task. am experienced in using nextjs.

- I will create a Brandkit page that showcases themarquis game. I will implement it at the `/brandkit` route

- I will setup a responsive layout structure, with breakpoints for different screen sizes, ensuring readability at all sizes.

depending on the contents @ [figma design](https://www.figma.com/design/urBxfs5QNCH4tnmk639ZTk/The-Marquis-Brandkit?node-id=1-179&node-type=frame&t=wvyipwm7QXWYhiRj-0&fuid=1291312080314383068) would determine the ETA.

kindly assign me

**Comment by Benjtalkshow** [comment]
@Buuh2511 and @gianalarcon 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can tackle this issue and make PR in 24hrs.

**Comment by abdegenius** [comment]
May I pick this up? I can comfortably handle this issues

**Comment by Ayoazeez26** [comment]
Can I work on this? I would implement the page and make sure it works and looks as expected on mobile and other screens

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
Mind if I take this issue?

**Comment by CollinsC1O** [comment]
Can I be assigned to this?

**Comment by ShantelPeters** [comment]
I'd like to take this issue.

**Comment by SudiptaPaul-31** [comment]
Will love to work on this issue.

**Comment by stephanniegb** [comment]
Let me try this one!  I extensive experience building responsive web pages, I’ll make sure it works smoothly and looks great on all screen sizes. 
Here are some of my recent projects for your reference:                                                                                                - https://tba-frontend-eta.vercel.app 
- https://scroll-transform-recreate.vercel.app
- https://three-js-galaxy-silk.vercel.app/

**Comment by josephpdf** [comment]
Hi! @Buuh2511
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Review the Existing PC Version:**
- Examine the current implementation of the Brandkit UI page on the PC version to understand its structure and functionality.
2. **Design Responsive Layouts:**
- Create responsive designs for different screen sizes (e.g., tablets, mobile devices) ensuring the UI adapts smoothly.
3. **Implement Responsive Styles:**
- Use CSS media queries and flexible grid layouts to adjust the UI components for various screen sizes.
-Ensure that all elements, such as images, text, and buttons, resize and reposition appropriately.
4. **Test Responsiveness:**
- Test the responsive UI on multiple devices and screen sizes to ensure it works well across all platforms.
- Use browser developer tools to simulate different screen sizes and orientations.
5. **Optimize Performance:**
- Ensure that the responsive design does not negatively impact the performance of the page.
-Optimize images and other assets for faster loading times on mobile devices.
6. **Verify Consistency:**
- Make sure the responsive version maintains the same look and feel as the PC version.
- Ensure that branding elements are consistent across all devices.

**Comment by gianalarcon** [comment]
All yours @Michaelkingsdev.  Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not our main branch

**Comment by Michaelkingsdev** [comment]
> All yours @Michaelkingsdev. Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not our main branch

Thanks a lot

**Comment by gianalarcon** [comment]
Hi @Michaelkingsdev . Any updates on this? We expect at least a draft PR in the upcoming hours. Thanks!

**Comment by gianalarcon** [comment]
Hi @Michaelkingsdev. Have you faced any issue? If there is no PR within the next few hours we will open the issue again

**Comment by Michaelkingsdev** [comment]
> Hi @Michaelkingsdev. Have you faced any issue? If there is no PR within the next few hours we will open the issue again for another candidate.

@gianalarcon 
I have opened a PR

**Comment by Luluameh** [comment]
Hi  @themarquis-ui-sc,
I’d be happy to take on this issue! I have experience working with responsive UI and implementing loading components. I can ensure the Brandkit page is fully responsive across all screen sizes, including 390px and PC versions, while maintaining functionality. I’ll also implement a preloaded loading component for smoother page transitions.

I can deliver this within the 24-hour timeline once assigned. Please let me know if I can start working on it!

**Comment by Buuh2511** [comment]
> Hi! @Buuh2511 I'm Joseph Poveda, I'm a member of the Dojo Coding community. A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems. To solve this issue I will:
> 
> 1. **Review the Existing PC Version:**
> 
> * Examine the current implementation of the Brandkit UI page on the PC version to understand its structure and functionality.
> 
> 2. **Design Responsive Layouts:**
> 
> * Create responsive designs for different screen sizes (e.g., tablets, mobile devices) ensuring the UI adapts smoothly.
> 
> 3. **Implement Responsive Styles:**
> 
> * Use CSS media queries and flexible grid layouts to adjust the UI components for various screen sizes.
>   -Ensure that all elements, such as images, text, and buttons, resize and reposition appropriately.
> 
> 4. **Test Responsiveness:**
> 
> * Test the responsive UI on multiple devices and screen sizes to ensure it works well across all platforms.
> * Use browser developer tools to simulate different screen sizes and orientations.
> 
> 5. **Optimize Performance:**
> 
> * Ensure that the responsive design does not negatively impact the performance of the page.
>   -Optimize images and other assets for faster loading times on mobile devices.
> 
> 6. **Verify Consistency:**
> 
> * Make sure the responsive version maintains the same look and feel as the PC version.
> * Ensure that branding elements are consistent across all devices.

Hi @josephpdf i would like to ask ,are u still available to work on this issue ?

**Comment by jahrulezfrancis** [comment]
Can I tackle this one? I’m confident I can handle this task efficiently, ensuring full responsiveness and proper loading components within the 24-hour timeline. Let me know if I should proceed!

**Comment by Benjtalkshow** [comment]
Hi, @gianalarcon 
Let me work on this issue. I will make PR in 12hrs and finalize my PR in 24hrs. Can this task be assigned to me?

**Comment by Agbeleshe** [comment]
I would love to be assigned this issue please. I have numerous experience creating responsive UI. I will be able to implement UI  and loader component within a day.

**Comment by 0xdevcollins** [comment]
Hello @gianalarcon  can I tackle this. I fully understand the issue and will make a PR in the next 24hrs

**Comment by HungNDB** [comment]
Could I take on this issue?

**Comment by OWK50GA** [comment]
I’d like to help with this.

**Comment by mimisavage** [comment]
Can I take this from here?

**Comment by aniruddhaaps** [comment]
To solve this problem I would:
Implement a responsive /brandkit page with proper layout adjustments to 390px width and all other screen sizes, compatible with the PC version.
Add a reusable loading component to handle redirects and preload where necessary, building on the prototype provided.
Test on multiple devices and screen sizes to ensure the website goes well seamlessly and responsively. Submit PR to develop branch within the 24-hour timeline.

**Comment by josephpdf** [comment]
> > Hi! @Buuh2511 I'm Joseph Poveda, I'm a member of the Dojo Coding community. A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems. To solve this issue I will:
> > 
> > 1. **Review the Existing PC Version:**
> > 
> > 
> > * Examine the current implementation of the Brandkit UI page on the PC version to understand its structure and functionality.
> > 
> > 
> > 2. **Design Responsive Layouts:**
> > 
> > 
> > * Create responsive designs for different screen sizes (e.g., tablets, mobile devices) ensuring the UI adapts smoothly.
> > 
> > 
> > 3. **Implement Responsive Styles:**
> > 
> > 
> > * Use CSS media queries and flexible grid layouts to adjust the UI components for various screen sizes.
> >   -Ensure that all elements, such as images, text, and buttons, resize and reposition appropriately.
> > 
> > 
> > 4. **Test Responsiveness:**
> > 
> > 
> > * Test the responsive UI on multiple devices and screen sizes to ensure it works well across all platforms.
> > * Use browser developer tools to simulate different screen sizes and orientations.
> > 
> > 
> > 5. **Optimize Performance:**
> > 
> > 
> > * Ensure that the responsive design does not negatively impact the performance of the page.
> >   -Optimize images and other assets for faster loading times on mobile devices.
> > 
> > 
> > 6. **Verify Consistency:**
> > 
> > 
> > * Make sure the responsive version maintains the same look and feel as the PC version.
> > * Ensure that branding elements are consistent across all devices.
> 
> Hi @josephpdf i would like to ask ,are u still available to work on this issue ?

Hi @Buuh2511 , Sure, I could try to solve the issue.

**Comment by gianalarcon** [comment]
closed with #86
