### ISSUE TITLE
Building Test Suite Frontend for StarkNet Wallet Interactions

### ISSUE THREAD

**Issue by Buuh2511** [The-Marquis-Gaming/themarquis-ui-sc#79]
### Test Cases for Deposit Function
1. UI Elements
   - Input field validation
   - Submit button states
   - Loading states
   - Success/Error messages

2. User Interactions
   - Enter valid amount
   - Enter invalid amount
   - Submit transaction
   - Cancel transaction

3. Integration
   - Mock successful transaction
   - Mock failed transaction
   - Test loading states
   - Test error handling
   
 ### Test Cases for Withdraw Function
 1. UI Elements
     - Balance display
     - Input validation
     - Button states
     - Transaction status

2. User Flows
   - Valid withdrawal
   - Invalid amount
   - Insufficient funds
   - Network errors

3. Transaction States
   - Pending
   - Success
   - Failed

## Proposed Solutions or Ideas

- Core Test Points:
  - Component rendering
  - User interactions
  - Error handling
  - Loading states
  - Form validation
  - Transaction flow
  - Event handling

**Comment by Buuh2511** [comment]
Gm sir, @gianalarcon. Could u pls review this issue, leave some comments to show more things we need to test

**Comment by 0xdevcollins** [comment]
Can I attempt this issue?

**Comment by Kingsuite** [comment]
Is it okay if I take this?

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Supa-mega** [comment]
Can I take this issue?

**Comment by Benjtalkshow** [comment]
Would love to tackle this!

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by Michaelkingsdev** [comment]
Can I tackle this one?

**Comment by od-hunter** [comment]
Hello, can I be assigned this issue? I'm good with testing, and my experience includes html, css, react, javaScript, typescript, solidity & Cairo.
Kindly assign, I'm ready to work

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by hoangkianh** [comment]
I can handle this task. I’m from the staknet.dart group

**Comment by Jemiiah** [comment]
Hello @gianalarcon I'd love to work on this issue please can I be assigned to work on it

**Comment by ikemHood** [comment]
I'd like to handle this task. @Buuh2511

I am a software developer with over 3 year of experience, I would setup a test suite with vitest and write test for every recomended components from the issue

**Comment by Buuh2511** [comment]
Hi everyone ! Please leave a comment how you would do it like what library you would use, how long it would take to do this task

**Comment by blessingbytes** [comment]
I am a frontend and blockchain developer specializing in creating intuitive user interfaces. I have experience with modern frameworks like React and smart contract development on platforms like Ethereum and Starknet.

pls may i try my hands on this?

**Comment by pheobeayo** [comment]
I'd be happy to do this.

**Comment by gianalarcon** [comment]
Hi @pheobeayo . Any updates on this? We expect at least a draft PR within the upcoming hours. Thanks!

**Comment by pheobeayo** [comment]
@gianalarcon I am working on it, I will create at least a draft PR before the end of today.

**Comment by Buuh2511** [comment]
Hi @pheobeayo. Any update on this ? Could u pls drop a draft PR ? it's been nearly 2 days and you said you could send PR

**Comment by pheobeayo** [comment]
Hello @Buuh2511 Please give me till the end of today, if no draft PR, you can reassign

**Comment by mimisavage** [comment]
Could I take on this issue?

**Comment by OlgaKush512** [comment]
Hello, my name is Olga, and I am a frontend developer. 
For solving this task, I plan to use: 
1. Jest, and possibly React Testing Library for testing the UI and writing unit tests. 
2. I would also use React Hook Form to validate the correctness of input fields. 
3. Additionally, I would use Mock Service Worker for mocking API requests and simulating different network errors.

**Comment by gianalarcon** [comment]
All yours @OlgaKush512. We expecte a draft PR within the upcoming hours. Thanks!

**Comment by gianalarcon** [comment]
Closed with #89

**Comment by OlgaKush512** [comment]
Thank you for this experience! =)

**Comment by gianalarcon** [comment]
Thanks for your contribution @OlgaKush512 Dm on discord: gianalarcon
