### ISSUE TITLE
Prepare for new release

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/themarquis-ui-sc#91]
## Issue Overview

- There has been many PRs that got merged, need to re-conciliate them with main branch

## Proposed Solutions or Ideas

- Clean, integrate and test whole website.
- Check missing relevant edge cases.

**Comment by Buuh2511** [comment]
## Overview

1. Code Integration
    - Pull latest changes from main branch
    - Identify and resolve any merge conflicts
    - Ensure all recent PRs are properly integrated
    - Verify code consistency across all merged components
2. Testing & Quality Assurance
    - Verify functionality of all integrated features
    - Test system performance after integration
    - Document any new bugs or issues discovered
3. Edge Case Analysis
    - Review and test critical user paths
    - Verify error handling and recovery

**Comment by gianalarcon** [comment]
closed with #92
