### ISSUE TITLE
Prepare for new release 

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/themarquis-ui-sc#95]
## Issue Overview

- There has been many PRs that got merged, need to re-conciliate them with main branch

## Proposed Solutions or Ideas

1. Code Integration
    - Pull latest changes from main branch
    - Identify and resolve any merge conflicts
    - Ensure all recent PRs/commit of develop branch are properly integrated
    - Verify code consistency across all merged components
2. Testing & Quality Assurance
    - Verify functionality of all integrated features
    - Test system performance after integration
    - Document any new bugs or issues discovered
3. Edge Case Analysis
    - Review and test critical user paths
    - Verify error handling and recovery

**Comment by estherbreath** [comment]
@gianalarcon Can I work on this issue, please

**Comment by jaykayudo** [comment]
@gianalarcon Can i be assigned this when ODHack 11 starts?

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by Judah04** [comment]
@gianalarcon I'd like to work on this task.

**Comment by Thibrac** [comment]
Could I be assigned to this?

**Comment by jedstroke** [comment]
I'd be happy to do this.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by Jake1698** [comment]
can I try this one pls?

**Comment by Amarjeet325** [comment]
Could I take a shot at this?

**Comment by codeZe-us** [comment]
Can I work on this?

**Comment by michojekunle** [comment]
Hi, I’d love to work on this task.

**Comment by GideonBature** [comment]
May I try my hand at this?

**Comment by gianalarcon** [comment]
All yours @Jake1698. Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours.
